version = 0.1

[default.global.parameters]
region = "ap-northeast-1"

[default.validate.parameters]

[default.deploy.parameters]
stack_name = "panda-tools"
s3_prefix = "panda-tools"
capabilities = "CAPABILITY_IAM"
resolve_s3 = true
image_repositories = []

[default.local_start_api.parameters]
host = "0.0.0.0"
