import {APIGatewayProxyEventV2} from "aws-lambda";
import {callExternalResponse, debug} from "./lib/env";
import Jimp from "jimp";

export default async function pandaToolsImagePanel(event: APIGatewayProxyEventV2, data: any) {

    const arg = data.arg //{url: argUrl, x: pos.x, y: pos.y},

    const arr = new Uint8Array(22*22*3/2)
    const arrSet = (uint8:number, i:number) => {
        const v = Math.floor(uint8 / 255 * 15)
        const idx = Math.floor(i/2)
        arr[idx] |= (i%2) ? v : v<<4
    }

    const image = await Jimp.read('https://assets.st-note.com/production/uploads/images/86872191/profile_9fe8e505a6b16e6b1c38b047f66485dd.png?width=104&height=104&dpr=2&crop=1:1,smart');
    image.resize(22,22).scan(0, 0, 22, 22, function (x, y, i) {
        // x, y is the position of this pixel on the image
        // idx is the position start position of this rgba tuple in the bitmap Buffer
        // this is the image
        const r = this.bitmap.data[i]
        const g = this.bitmap.data[i + 1]
        const b = this.bitmap.data[i + 2]
        const a = this.bitmap.data[i + 3]
        const p = (x + 22*y) * 3
        arrSet(r, p)
        arrSet(g, p+1)
        arrSet(b, p+2)
    });
    const b64 = Buffer.from(arr).toString("base64");

    if (debug) {
        console.info('b64:', b64)
        //2023-12-26T03:51:26.957Z	93cc1ec0-c2cf-401b-8d56-0fede898b171	INFO
        // b64: AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADQANAA0ADQANAA0ADQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADQANAA0ADQANAA0ADQANAAAAAAIEAgQCBAAAAAAAAAAAAAAAAAAAAAAADQANAA0ADQANAA0ADQANAQYCBAIEAgQCBAIEAgQCBAAAAAAAAAAAAAAAAAANAA0ADQANAA0ADQANAQYCBAIEAgQCBAIEAgQCBAIEAAAAAAAAAAAAAAAAAA0ADQANAA0AAAAAAAACBAIEAgQCBAIEAgQCBAIEAgQAAAAAAAAAAAAAAAAADQANAA0ADQAAAAAAAAIEAgQCBAIEAgQCBAIEAgQCBAAAAAAAAAAAAAAAAAANAA0ADQANAA0ADQANAQYCBAIEAgQCBAIEAgQCBAIEAAAAAAAAAAAAAAAAAA0ADQANAA0ADQANAA0ADQEGAgQCBAIEAgQCBAIEAgQAAAAAAAAAAAAAAAAAAAANAA0ADQANAA0ADQANAA0AAAAAAgQCBAIEAAAAAAAAAAAAAAAAAAAAAAAAAAAADQANAA0ADQANAA0ADQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        //2023-12-26T04:42:49.531Z	ebd11aba-354e-4520-94b7-4004df9cdf74	INFO
        // b64: AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAnQCdAJ0AnQCdAJ0AnQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAnQCdAJ0AnQCdAJ0AnQCdAAAAAAI0AjQCNAAAAAAAAAAAAAAAAAAAAAAAnQCdAJ0AnQCdAJ0AnQCdAUYCNAI0AjQCNAI0AjQCNAAAAAAAAAAAAAAAAACdAJ0AnQCdAJ0AnQCdAUYCNAI0AjQCNAI0AjQCNAI0AAAAAAAAAAAAAAAAAJ0AnQCdAJ0AAAAAAAACNAI0AjQCNAI0AjQCNAI0AjQAAAAAAAAAAAAAAAAAnQCdAJ0AnQAAAAAAAAI0AjQCNAI0AjQCNAI0AjQCNAAAAAAAAAAAAAAAAACdAJ0AnQCdAJ0AnQCdAUYCNAI0AjQCNAI0AjQCNAI0AAAAAAAAAAAAAAAAAJ0AnQCdAJ0AnQCdAJ0AnQFGAjQCNAI0AjQCNAI0AjQAAAAAAAAAAAAAAAAAAACdAJ0AnQCdAJ0AnQCdAJ0AAAAAAjQCNAI0AAAAAAAAAAAAAAAAAAAAAAAAAAAAnQCdAJ0AnQCdAJ0AnQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    }

    return callExternalResponse(200, b64);
}
